<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E0($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 100000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[1], $test[1], $ls, 1, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H0($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#(?<=Alcatel-)[^/\\s]+#', $useragent),
    1 => fiftyone_degrees_preg_match_all('#.+#', $useragent));
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/444')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139063,317420,841, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/444');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606A'), 1 => array(0 => 'Alcatel-OT-606A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606A'), 1 => array(0 => 'Alcatel-OT-606A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/010_05 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606/010_05 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/010_03 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,117741,841, 'Alcatel-OT-606/010_03 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A', 1 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800', 1 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A', 1 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,112031,841, 'Alcatel-OT-800/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL-OT871A/980 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,112031,841, 'ALCATEL-OT871A/980 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802Yation'), 1 => array(0 => 'Alcatel-OT-802Yation/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802Yation/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802A'), 1 => array(0 => 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802A'), 1 => array(0 => 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802Y'), 1 => array(0 => 'Alcatel-OT-802Y/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802Y/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802A', 1 => 'OT-802A'), 1 => array(0 => 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802'), 1 => array(0 => 'Alcatel-OT-802/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323414,139459,112031,841, 'Alcatel-OT-802/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355A'), 1 => array(0 => 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355D'), 1 => array(0 => 'Alcatel-OT-355D/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355D/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 model-bouygues ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355/1.0 model-bouygues ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355A'), 1 => array(0 => 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199984,139459,117741,841, 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808', 1 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808A'), 1 => array(0 => 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808A'), 1 => array(0 => 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/010_01 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,112031,841, 'Alcatel-OT-808/010_01 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL-OT510A/382 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(697808,139459,112031,841, 'ALCATEL-OT510A/382 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OH5'), 1 => array(0 => 'Alcatel-OH5/1.0 UP.Browser/6.1.0.7.7 (GUI) MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(432266,139459,194008,841, 'Alcatel-OH5/1.0 UP.Browser/6.1.0.7.7 (GUI) MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710'), 1 => array(0 => 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710D'), 1 => array(0 => 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710A'), 1 => array(0 => 'Alcatel-OT-710A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710A'), 1 => array(0 => 'Alcatel-OT-710A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710', 1 => 'OT-710'), 1 => array(0 => 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710'), 1 => array(0 => 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710D'), 1 => array(0 => 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,117741,841, 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806'), 1 => array(0 => 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806'), 1 => array(0 => 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04E');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A', 1 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806D'), 1 => array(0 => 'Alcatel-OT-806D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806'), 1 => array(0 => 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,112031,841, 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255D'), 1 => array(0 => 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255', 1 => 'OT-255'), 1 => array(0 => 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255A'), 1 => array(0 => 'Alcatel-OT-255A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255'), 1 => array(0 => 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255'), 1 => array(0 => 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255D'), 1 => array(0 => 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(183070,139459,117741,841, 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-799'), 1 => array(0 => 'Alcatel-OT-799/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(389897,139459,112031,841, 'Alcatel-OT-799/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-799A'), 1 => array(0 => 'Alcatel-OT-799A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(389897,139459,112031,841, 'Alcatel-OT-799A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880A'), 1 => array(0 => 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880'), 1 => array(0 => 'Alcatel-OT-880/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880A'), 1 => array(0 => 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880A', 1 => 'OT-880A'), 1 => array(0 => 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880'), 1 => array(0 => 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880'), 1 => array(0 => 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(139387,139459,112031,841, 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305'), 1 => array(0 => 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(221176,139459,117741,841, 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305', 1 => 'OT-305'), 1 => array(0 => 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(221176,139459,117741,841, 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305A'), 1 => array(0 => 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(221176,139459,117741,841, 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305A'), 1 => array(0 => 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(221176,139459,117741,841, 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305'), 1 => array(0 => 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(221176,139459,117741,841, 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807A'), 1 => array(0 => 'Alcatel-OT-807A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,112031,841, 'Alcatel-OT-807A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,112031,841, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/05S')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,112031,841, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/05S');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04N')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,112031,841, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04N');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807D'), 1 => array(0 => 'Alcatel-OT-807D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,112031,841, 'Alcatel-OT-807D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708A'), 1 => array(0 => 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708A'), 1 => array(0 => 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C AppEngine-Google; (+http://code.google.com/appengine; appid: 360hours)')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C AppEngine-Google; (+http://code.google.com/appengine; appid: 360hours)');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708', 1 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(150438,139459,117741,841, 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/444')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(640981,139063,317420,841, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/444');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/355')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(640981,139063,317420,841, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/355');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/352')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(640981,139063,317420,841, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/352');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-807a')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239835,139459,16149,841, 'alcatel-ot-807a');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,117741,841, 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A', 1 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,117741,841, 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(322838,139459,117741,841, 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-660'), 1 => array(0 => 'Alcatel-OT-660/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(286971,139459,117741,841, 'Alcatel-OT-660/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-660A'), 1 => array(0 => 'Alcatel-OT-660A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(286971,139459,117741,841, 'Alcatel-OT-660A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-606a')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,16149,841, 'alcatel-ot-606a');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-606a Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219512,139459,16149,841, 'alcatel-ot-606a Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 model-Bouygues ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(331339,139459,117741,841, 'Alcatel-OT-505/1.0 model-Bouygues ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 version 010 03 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(331339,139459,117741,841, 'Alcatel-OT-505/1.0 version 010 03 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(331339,139459,117741,841, 'Alcatel-OT-505/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600A'), 1 => array(0 => 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-565'), 1 => array(0 => 'Alcatel-OT-565/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-565/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600A'), 1 => array(0 => 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'GLAMPHONE-ELLE-A'), 1 => array(0 => 'Alcatel-GLAMPHONE-ELLE-A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-GLAMPHONE-ELLE-A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S321A'), 1 => array(0 => 'Alcatel-OT-S321A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-S321A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S626A'), 1 => array(0 => 'Alcatel-OT-S626A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-S626A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C820'), 1 => array(0 => 'Alcatel-OT-C820/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-C820/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-360A'), 1 => array(0 => 'Alcatel-OT-360A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-360A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-380'), 1 => array(0 => 'Alcatel-OT-380/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,117741,841, 'Alcatel-OT-380/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600'), 1 => array(0 => 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(231626,139459,117741,841, 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600'), 1 => array(0 => 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(231626,139459,117741,841, 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/010_02 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(171249,139459,117741,841, 'Alcatel-OT-363/010_02 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363A'), 1 => array(0 => 'Alcatel-OT-363A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(171249,139459,117741,841, 'Alcatel-OT-363A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(171249,139459,117741,841, 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(171249,139459,117741,841, 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(171249,139459,117741,841, 'Alcatel-OT-363/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(640981,139063,596455,841, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-706'), 1 => array(0 => 'Alcatel-OT-706/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(314395,139459,117741,841, 'Alcatel-OT-706/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-706A'), 1 => array(0 => 'Alcatel-OT-706A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(314395,139459,117741,841, 'Alcatel-OT-706A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S319'), 1 => array(0 => 'Alcatel-OT-S319/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(289323,139459,117741,841, 'Alcatel-OT-S319/1.0 model-orange ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S319'), 1 => array(0 => 'Alcatel-OT-S319/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(289323,139459,117741,841, 'Alcatel-OT-S319/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S319A'), 1 => array(0 => 'Alcatel-OT-S319A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(289323,139459,117741,841, 'Alcatel-OT-S319A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701A'), 1 => array(0 => 'Alcatel-OT-C701A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(217856,139459,117741,841, 'Alcatel-OT-C701A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701A'), 1 => array(0 => 'Alcatel-OT-C701A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(217856,139459,117741,841, 'Alcatel-OT-C701A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701'), 1 => array(0 => 'Alcatel-OT-C701/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(217856,139459,117741,841, 'Alcatel-OT-C701/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-300'), 1 => array(0 => 'Alcatel-OT-300/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(363613,139459,117741,841, 'Alcatel-OT-300/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303A'), 1 => array(0 => 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(218072,139459,117741,841, 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303'), 1 => array(0 => 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(218072,139459,117741,841, 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303'), 1 => array(0 => 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(218072,139459,117741,841, 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303A'), 1 => array(0 => 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(218072,139459,117741,841, 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621'), 1 => array(0 => 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(249645,139459,117741,841, 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621', 1 => 'OT-S621'), 1 => array(0 => 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(249645,139459,117741,841, 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621A'), 1 => array(0 => 'Alcatel-OT-S621A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(249645,139459,117741,841, 'Alcatel-OT-S621A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'TH3'), 1 => array(0 => 'Alcatel-TH3/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(231258,139459,18014,841, 'Alcatel-TH3/1.0 UP.Browser/6.2.ALCATEL MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-508A'), 1 => array(0 => 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C  Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350464,139459,117741,841, 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C  Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-508A'), 1 => array(0 => 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350464,139459,117741,841, 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320', 1 => 'OT-S320'), 1 => array(0 => 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(360445,139459,117741,841, 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320'), 1 => array(0 => 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(360445,139459,117741,841, 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320'), 1 => array(0 => 'Alcatel-OT-S320/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(360445,139459,117741,841, 'Alcatel-OT-S320/1.0 model-orange ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320A'), 1 => array(0 => 'Alcatel-OT-S320A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(360445,139459,117741,841, 'Alcatel-OT-S320A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MISS-SIXTY-MSX-10'), 1 => array(0 => 'Alcatel-MISS-SIXTY-MSX-10/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(378631,139459,112031,841, 'Alcatel-MISS-SIXTY-MSX-10/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-v770'), 1 => array(0 => 'Alcatel-OT-v770/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(245463,139459,117741,841, 'Alcatel-OT-v770/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BH4R'), 1 => array(0 => 'Alcatel-BH4R/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(338500,139459,18014,841, 'Alcatel-BH4R/1.0 UP.Browser/6.2.ALCATEL MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BH4'), 1 => array(0 => 'Alcatel-BH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(338500,139459,18014,841, 'Alcatel-BH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BH4'), 1 => array(0 => 'Alcatel-BH4/1.0 UP.Browser/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(338500,139459,18014,841, 'Alcatel-BH4/1.0 UP.Browser/6.2');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S520'), 1 => array(0 => 'Alcatel-OT-S520/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343255,139459,117741,841, 'Alcatel-OT-S520/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S520A'), 1 => array(0 => 'Alcatel-OT-S520A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343255,139459,117741,841, 'Alcatel-OT-S520A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-565A'), 1 => array(0 => 'Alcatel-OT-565A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(217568,139459,117741,841, 'Alcatel-OT-565A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V670A'), 1 => array(0 => 'Alcatel-OT-V670A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(312011,139459,117741,841, 'Alcatel-OT-V670A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V670'), 1 => array(0 => 'Alcatel-OT-V670/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(312011,139459,117741,841, 'Alcatel-OT-V670/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-I650'), 1 => array(0 => 'Alcatel-OT-I650/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(364917,139459,117741,841, 'Alcatel-OT-I650/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'TH4'), 1 => array(0 => 'Alcatel-TH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,18014,841, 'Alcatel-TH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S853'), 1 => array(0 => 'Alcatel-OT-S853/1.0 UP.Browser/7.1 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(237092,139459,77193,841, 'Alcatel-OT-S853/1.0 UP.Browser/7.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C552'), 1 => array(0 => 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(262477,139459,77193,841, 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C552'), 1 => array(0 => 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(262477,139459,77193,841, 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0 Profile/MIDP-2.0 Configuration/CLDC-1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C552a'), 1 => array(0 => 'Alcatel-OT-C552a/1.0 UP.Browser/7.1.0.i.1.105 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(262477,139459,77193,841, 'Alcatel-OT-C552a/1.0 UP.Browser/7.1.0.i.1.105 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C700A'), 1 => array(0 => 'Alcatel-OT-C700A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(342030,139459,117741,841, 'Alcatel-OT-C700A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C700'), 1 => array(0 => 'Alcatel-OT-C700/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(342030,139459,117741,841, 'Alcatel-OT-C700/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Mandarina-Duck'), 1 => array(0 => 'Alcatel-Mandarina-Duck/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(235796,139459,117741,841, 'Alcatel-Mandarina-Duck/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C707'), 1 => array(0 => 'Alcatel-OT-C707/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(245103,139459,117741,841, 'Alcatel-OT-C707/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C550'), 1 => array(0 => 'Alcatel-OT-C550/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(264137,139459,117741,841, 'Alcatel-OT-C550/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Crystal'), 1 => array(0 => 'Alcatel-Crystal/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(305971,139459,117741,841, 'Alcatel-Crystal/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BG3'), 1 => array(0 => 'Alcatel-BG3/1.0 UP.Browser/5.0.3.3.11')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(250653,139459,49054,841, 'Alcatel-BG3/1.0 UP.Browser/5.0.3.3.11');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BG3'), 1 => array(0 => 'Alcatel-BG3/1.0 UP.Browser/5.0.3.1.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(250653,139459,49054,841, 'Alcatel-BG3/1.0 UP.Browser/5.0.3.1.2');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BG3-color'), 1 => array(0 => 'Alcatel-BG3-color/1.0 UP.Browser/5.0.3.3.11')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(250653,139459,49054,841, 'Alcatel-BG3-color/1.0 UP.Browser/5.0.3.3.11');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-280'), 1 => array(0 => 'Alcatel-OT-280/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(250939,139459,117741,841, 'Alcatel-OT-280/1.0 model-orange ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-280'), 1 => array(0 => 'Alcatel-OT-280/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(250939,139459,117741,841, 'Alcatel-OT-280/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C630'), 1 => array(0 => 'Alcatel-OT-C630/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(432194,139459,117741,841, 'Alcatel-OT-C630/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C717'), 1 => array(0 => 'Alcatel-OT-C717/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(256152,139459,117741,841, 'Alcatel-OT-C717/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C717A'), 1 => array(0 => 'Alcatel-OT-C717A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(256152,139459,117741,841, 'Alcatel-OT-C717A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-383A'), 1 => array(0 => 'Alcatel-OT-383A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(376543,139459,117741,841, 'Alcatel-OT-383A/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MissSixty'), 1 => array(0 => 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(378631,139459,117741,841, 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MissSixty'), 1 => array(0 => 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(378631,139459,117741,841, 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MissSixty', 1 => 'MissSixty'), 1 => array(0 => 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(378631,139459,117741,841, 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-315M'), 1 => array(0 => 'Alcatel-OT-315M/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(388745,139459,117741,841, 'Alcatel-OT-315M/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'ELLE-N1'), 1 => array(0 => 'Alcatel-ELLE-N1/1.0 UP.Browser/7.1 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,77193,841, 'Alcatel-ELLE-N1/1.0 UP.Browser/7.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,16149,841, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(254640,139459,16149,841, 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V570A'), 1 => array(0 => 'Alcatel-OT-V570A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(339580,139459,117741,841, 'Alcatel-OT-V570A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-216'), 1 => array(0 => 'Alcatel-OT-216/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(339868,139459,117741,841, 'Alcatel-OT-216/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S920'), 1 => array(0 => 'Alcatel-OT-S920/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q04A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343471,139459,83529,841, 'Alcatel-OT-S920/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q04A');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S218'), 1 => array(0 => 'Alcatel-OT-S218/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(376183,139459,117741,841, 'Alcatel-OT-S218/1.0 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'ELLE-N3'), 1 => array(0 => 'Alcatel-ELLE-N3/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(377623,139459,117741,841, 'Alcatel-ELLE-N3/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OH2'), 1 => array(0 => 'Alcatel-OH2/1.0 ObigoInternetBrowser/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139459,16149,841, 'Alcatel-OH2/1.0 ObigoInternetBrowser/2.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C825'), 1 => array(0 => 'Alcatel-OT-C825/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(267014,139459,117741,841, 'Alcatel-OT-C825/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-710a/UC Browser7.0.0.41/69/4249 Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(209382,139459,11322,841, 'alcatel-ot-710a/UC Browser7.0.0.41/69/4249 Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Mandarina-Duck-MOON'), 1 => array(0 => 'Alcatel-Mandarina-Duck-MOON/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(347943,139459,117741,841, 'Alcatel-Mandarina-Duck-MOON/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-808  Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(153247,139459,16149,841, 'alcatel-ot-808  Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C550'), 1 => array(0 => 'Alcatel-OT-C550')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(264137,139459,16149,841, 'Alcatel-OT-C550');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BH4'), 1 => array(0 => 'Alcatel-BH4/1.0 UP.Browser/6.1.0.6.1 (GUI) MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(338500,139459,194008,841, 'Alcatel-BH4/1.0 UP.Browser/6.1.0.6.1 (GUI) MMP/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C552a'), 1 => array(0 => 'Alcatel-OT-C552a')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(262477,139459,16149,841, 'Alcatel-OT-C552a');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701'), 1 => array(0 => 'Alcatel-OT-C701')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(217856,139459,16149,841, 'Alcatel-OT-C701');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C825'), 1 => array(0 => 'Alcatel-OT-C825')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(267014,139459,16149,841, 'Alcatel-OT-C825');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OH5'), 1 => array(0 => 'Alcatel-OH5')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(432266,139459,16149,841, 'Alcatel-OH5');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'TH3'), 1 => array(0 => 'Alcatel-TH3')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(231258,139459,16149,841, 'Alcatel-TH3');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Mandarina-Duck'), 1 => array(0 => 'Alcatel-Mandarina-Duck/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(235796,139459,16149,841, 'Alcatel-Mandarina-Duck/1.0');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V670'), 1 => array(0 => 'Alcatel-OT-V670/')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(312011,139459,16149,841, 'Alcatel-OT-V670/');
    $ls = $ns;
  }
  return $dl;
}
