<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E125($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 100000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H125($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#^[^\\(]+#', $useragent));
  $ns = E125($segments, array(0 => array(0 => 'coccoc/1.0 ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(292268,292349,185962,292261, 'coccoc/1.0 (http://help.coccoc.vn/) AppEngine-Google; (+http://code.google.com/appengine; appid: s~doingfly)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,185962,841, 'AppEngine-Google; (+http://code.google.com/appengine; appid: s~getfavicon27)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Public Hub ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,185962,841, 'Public Hub (+http://pubsubhubbub.appspot.com; 1 subscribers) AppEngine-Google; (+http://code.google.com/appengine; appid: pubsubhubbub)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'facebookexternalhit/1.0 ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(292268,292349,185962,506051, 'facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php) AppEngine-Google; (+http://code.google.com/appengine; appid: rtweetme)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Python-urllib/2.7 AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,16149,841, 'Python-urllib/2.7 AppEngine-Google; (+http://code.google.com/appengine; appid: s~hr-pulsesubscriber)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Python-urllib/2.5 AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,16149,841, 'Python-urllib/2.5 AppEngine-Google; (+http://code.google.com/appengine; appid: ggghelper)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Python-urllib/1.17 AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,16149,841, 'Python-urllib/1.17 AppEngine-Google; (+http://code.google.com/appengine; appid: s~hr-pulsesubscriber)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Feedfetcher-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(292268,292349,185962,508787, 'Feedfetcher-Google; (+http://www.google.com/feedfetcher.html; 2 subscribers; feed-id=X) AppEngine-Google; (+http://code.google.com/appengine; appid: voxelshader)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'iPhone AppleWebKit AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(105356,88488,16149,841, 'iPhone AppleWebKit AppEngine-Google; (+http://code.google.com/appengine; appid: qmksync)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'iPad AppleWebKit AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(287883,88488,16149,841, 'iPad AppleWebKit AppEngine-Google; (+http://code.google.com/appengine; appid: qmksync)');
    $ls = $ns;
  }
  $ns = E125($segments, array(0 => array(0 => 'Mozilla-Firefox5.0 AppEngine-Google; ')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,292349,159972,841, 'Mozilla-Firefox5.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~zhoulixia86)');
    $ls = $ns;
  }
  return $dl;
}
