<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E127($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 10000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[1], $test[1], $ls, 10000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H127($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#Netscape/\\d\\.\\d#', $useragent),
    1 => fiftyone_degrees_preg_match_all('#Netscape\\d/\\d\\.\\d#', $useragent));
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,63882,841, 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; FunWebProducts; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0) Netscape/8.0.3.4');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,63882,841, 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; FunWebProducts; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0; .NET CLR 2.0.50727) Netscape/8.1.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,33618,841, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Netscape/8.0.4');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,33618,841, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) Netscape/8.1.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,508794,841, 'Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.4) Gecko Netscape/7.1 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,517959,841, 'Mozilla/5.0 (Windows; U; Win 9x 4.90; ja-JP; rv:1.0.1) Gecko/X Netscape/7.0');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,517959,841, 'Mozilla/7.0 (Windows; U; Windows NT 5.1; en-US; rv:0.9.2) Gecko/X Netscape/7.0');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,513379,841, '(\'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.5) Gecko/X Netscape/8.1\', \'Netscape 8.1, Windows XP\')');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(60425,139753,517959,841, 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; fr-FR; rv:1.0.2) Gecko/X Netscape/7.02');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,515228,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:0.9.2) Gecko/X Netscape6/6.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,522692,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; ja-JP; rv:1.7.5) Gecko/X Netscape/8.0.4');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,529413,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:0.9.4.1) Gecko/X Netscape6/6.2.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,513379,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.5) Gecko/X Netscape/8.1.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,506044,517959,841, 'Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.0.1) Gecko/X Netscape/7.0');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,523697,841, 'Mozilla/5.0 (Windows; U; Win98; en-US; m18) Gecko/X Netscape6/6.01');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,508794,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.4) Gecko/X Netscape/7.1 (ax; CDonDemand-Dom)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,522692,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.5) Gecko/X Netscape/8.0.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,356320,511532,841, 'Mozilla/5.0 (Windows; U; Win95; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,64735,513379,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.7.5) Gecko/X Netscape/8.1.3');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,353937,515228,841, 'Mozilla/5.0 (Windows; U; WinNT4.0; en-US) Netscape6/6.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,529413,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; de-DE; rv:0.9.4.1) Gecko/X Netscape6/6.2.3');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,114029,508794,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; de-DE; rv:1.4) Gecko/X Netscape/7.1 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,511532,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; ja-JP; rv:1.7.2) Gecko/X Netscape/7.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,515228,841, 'Mozilla/5.0 (Windows; U; Win 9x 4.90; de-DE; rv:0.9.2) Gecko/X Netscape6/6.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,114029,513379,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.7.5) Gecko/X Netscape/8.1.3');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,114029,511532,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax;nscd1)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139063,529413,841, 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:0.9.4) Gecko/X Netscape6/6.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,64735,508794,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE; rv:1.4) Gecko/X Netscape/7.1 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,44793,515228,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:0.9.2) Gecko/X Netscape6/6.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139063,517959,841, 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.0.2) Gecko/X Netscape/7.01');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,353937,508794,841, 'Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.4) Gecko/X Netscape/7.1 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,114029,522692,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.7.5) Gecko/X Netscape/8.0.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(60425,139753,511532,841, 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,64735,511532,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax;nscd1)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/8.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,513379,841, 'Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.7.5) Gecko/X Netscape/8.1.3');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,64735,529413,841, 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:0.9.4.1) Gecko/X Netscape6/6.2.3');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.0'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,517959,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; de-DE; rv:1.0.2) Gecko/X Netscape/7.01');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,508794,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; ja-JP; rv:1.4) Gecko/X Netscape/7.1 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,511532,841, 'Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.1'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(60425,139753,508794,841, 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.4) Gecko/X Netscape/7.1');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,65677,511532,841, 'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.7.2) Gecko/X Netscape/7.2 (ax)');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139063,523697,841, 'Mozilla/5.0 (X11; U; Linux 2.4.2-2 i586; en-US; m18) Gecko/X Netscape6/6.01');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => array(0 => 'Netscape/7.2'), 1 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,139063,511532,841, 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.2) Gecko/X Netscape/7.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,240627,529413,841, 'Mozilla/5.0 (Windows; U; Win98; fr-FR; rv:0.9.4.1) Gecko/X Netscape6/6.2.2');
    $ls = $ns;
  }
  $ns = E127($segments, array(0 => NULL, 1 => array(0 => 'Netscape6/6.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,353937,529413,841, 'Mozilla/5.0 (Windows; U; WinNT4.0; en-CA; rv:0.9.4) Gecko/X Netscape6/6.2.1');
    $ls = $ns;
  }
  return $dl;
}
