<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0.
 *
 * If a copy of the MPL was not distributed with this file, You can obtain one
 * at http://mozilla.org/MPL/2.0/.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined
 * by the Mozilla Public License, v. 2.0.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E44($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H44($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'KWC-Buckle/ UP.Browser/7.2.7.2.549 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ UP.Browser/7.2.7.2.541 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ABN1004 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ UP.Browser/7.2.7.2.549 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ UP.Browser/7.2.7.2.541 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ABO1008 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ABO1102 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ABO1107 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Buckle/ABO1008 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13513,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABU1001 UP.Browser/7.2.7.2.552 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABR1003 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300-C/ACF1002 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABR1001 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABQ1000 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABQ1000 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABQ1103 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABQ1103 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300-C/ACF1002 UP.Browser/7.2.7.2.549 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABU1001 UP.Browser/7.2.7.2.552 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABR1001 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S2300/ABR1003 UP.Browser/7.2.7.2.551 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15089,5214,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/ UP.Browser/7.2.6.1.839 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/ UP.Browser/7.2.6.1.838 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1002 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1007 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1007 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1002 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1001 UP.Browser/7.2.6.1.841 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/ UP.Browser/7.2.6.1.838 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/ UP.Browser/7.2.6.1.839 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/0320 UP.Browser/7.2.6.1.714 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1009 UP.Browser/7.2.6.1.839 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/10081 UP.Browser/7.2.6.1.839 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1007 UP.Browser/7.2.6.1.839 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1300/1009 UP.Browser/7.2.6.1.839 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(11731,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Torino/ UP.Browser/7.2.7.2.561 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13616,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Torino/ UP.Browser/7.2.7.2.561 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13616,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Rio/ACI1005 UP.Browser/7.2.7.2.563 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15675,5214,3487,18092, $ua);
  }
  $ua = 'KWC-Rio/ACI1003 UP.Browser/7.2.7.2.563 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15675,5214,3487,18092, $ua);
  }
  $ua = 'KWC-Rio/ACJ1005 UP.Browser/7.2.7.2.562 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15675,5214,3487,18092, $ua);
  }
  $ua = 'KWC-Rio/ABY1009 UP.Browser/7.2.7.2.562 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15675,5214,3487,18092, $ua);
  }
  $ua = 'KWC-Rio/ABY1009 UP.Browser/7.2.7.2.562 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15675,5214,3487,18092, $ua);
  }
  $ua = 'KWC-Glide/ UP.Browser/7.2.7.2.541 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12343,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Glide/ UP.Browser/7.2.7.2.541 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12343,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Glide/ABJ0305 UP.Browser/7.2.7.2.536 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12343,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Lightpipe/ UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14497,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Lightpipe/ UP.Browser/7.2.7.2.531 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14497,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Lightpipe/1002 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14497,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Lightpipe/1003 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14497,17017,3487,18092, $ua);
  }
  $ua = 'KWC-Lightpipe/10013 UP.Browser/7.2.7.2.510 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14497,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1004 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1004 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1003 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1003 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1002 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1002 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1103 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1103 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-A/1102 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13804,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/ZQ1003 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/AAN1004 UP.Browser/7.2.7.2.530 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/AAN1004 UP.Browser/7.2.7.2.530 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/AAN1002 UP.Browser/7.2.7.2.530 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/AAN1002 UP.Browser/7.2.7.2.530 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/ZQ1000 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/ZQ1003 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M2000/AAN0314 UP.Browser/7.2.7.2.528 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12393,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S4000/ UP.Browser/7.2.6.1.794 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12373,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S4000/ UP.Browser/7.2.6.1.794 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12373,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S4000/10033 UP.Browser/7.2.6.1.644 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12373,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S4000/10022 UP.Browser/7.2.6.1.838 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12373,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S4000/10019 UP.Browser/7.2.6.1.803 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12373,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-V/1001 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13635,17017,3487,18092, $ua);
  }
  $ua = 'KWC-S1310-V/1001 UP.Browser/7.2.6.1.840 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13635,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M1000/1.0.01 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12510,17017,3625,18092, $ua);
  }
  $ua = 'KWC-M1000/1.1.00 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12510,17017,3625,18092, $ua);
  }
  $ua = 'KWC-M1000/1.0.07 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12510,17017,3625,18092, $ua);
  }
  $ua = 'KWC-M1000/1.0.07 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12510,17017,3625,18092, $ua);
  }
  $ua = 'KWC-M1000/1.0.06 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12510,17017,3625,18092, $ua);
  }
  $ua = 'KWC-E2000/1013 UP.Browser/7.2.6.1.567 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/1022 UP.Browser/7.2.6.1.537 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/1011 UP.Browser/7.2.6.1.567 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/10086 UP.Browser/7.2.6.1.537 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/1017 UP.Browser/7.2.6.1.537 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/1016 UP.Browser/7.2.6.1.537 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-E2000/1003 UP.Browser/7.2.6.1.475 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12383,17017,3487,18092, $ua);
  }
  $ua = 'KWC-laylo/AAR10044 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14226,17017,3487,18092, $ua);
  }
  $ua = 'KWC-M1400/AAZ10043 UP.Browser/7.2.7.2.536 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14226,17017,3487,18092, $ua);
  }
  $ua = 'KWC-laylo/AAR1004 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(14226,17017,3487,18092, $ua);
  }
  $ua = 'KWC-K127/1204 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15674,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K127/1204 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15674,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K127/11031 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15674,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K127/1002 UP.Browser/6.2.3.9.g.1.110 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15674,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K325/1.1.00 UP.Browser/6.2.3.9.g.1.107 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13419,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K325/1.1.00 UP.Browser/6.2.3.9.g.1.107 (GUI) MMP/2.0 Novarra-Vision/8.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13419,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K325/1.0.04 UP.Browser/6.2.3.9.g.1.107 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13419,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K24/1.0.06 UP.Browser/6.2.3.9.g.1.109 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13743,17017,3625,18092, $ua);
  }
  $ua = 'KWC-K24/1.0.07 UP.Browser/6.2.3.9.g.1.109 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(13743,17017,3625,18092, $ua);
  }
  $ua = 'KWC-E1100/1002 UP.Browser/7.2.7.2.531 (GUI) MMP/2.0';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(12345,17017,3487,18092, $ua);
  }
  $ua = 'KWC-K127';
  $ns = E44($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(15674,17017,17470,18092, $ua);
  }
  return $dl;
}
