<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E55($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 1, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H55($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#KDDI-\\w+#', $useragent));
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC31 UP.Browser/6.2.0.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN31 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN37 UP.Browser/6.2.0.11.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-CA32 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SA38 UP.Browser/6.2.0.11.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA24')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-CA24 UP.Browser/6.2.0.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS39 UP.Browser/6.2.0.11.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN38 UP.Browser/6.2.0.11.2.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN3H UP.Browser/6.2_7.2.7.1.K.2.221 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC41')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC41 UP.Browser/6.2.0.16.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC43')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC43 UP.Browser/6.2.0.17.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC46')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC46 UP.Browser/6.2_7.2.7.1.K.7.108 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SA3B UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SH35 UP.Browser/6.2_7.2.7.1.K.2.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN3C UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-HI38 UP.Browser/6.2.0.11.1.3.110 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN39 UP.Browser/6.2.0.11.2.1e (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3K')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3K UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3A UP.Browser/6.2.0.11.2.1e (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SH3C UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-CA3B UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3Y')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3Y UP.Browser/6.2_7.2.7.1.K.7.112 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3Z')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3Z UP.Browser/6.2_7.2.7.1.K.7.112 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3F')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-HI3F UP.Browser/6.2_7.2.7.1.K.3.354 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3U')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN3U UP.Browser/6.2_7.2.7.1.K.7.112 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SH37 UP.Browser/6.2_7.2.7.1.K.2.232 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-HI3G UP.Browser/6.2_7.2.7.1.K.3.354 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3K')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-CA3K UP.Browser/6.2_7.2.7.1.K.7.112 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3M')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3M UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SA3D UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SA3E UP.Browser/6.2_7.2.7.1.K.2.232 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-CA3D UP.Browser/6.2_7.2.7.1.K.3.354 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-FJ31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-FJ31 UP.Browser/6.2_7.2.7.1.K.8.160 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3V')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-SN3V UP.Browser/6.2_7.2.7.1.K.7.113 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3L')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-TS3L UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC38 UP.Browser/6.2.0.11.1.2.2e (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC4A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,18014,841, 'KDDI-KC4A UP.Browser/6.2_7.2.7.1.K.7.1.104 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(370400,370393,18014,355759, 'KDDI-CA31 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0 (compatible; ichiro/mobile goo; +http://search.goo.ne.jp/option/use/sub4/sub4-1/)');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3S')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(490936,370393,18014,841, 'KDDI-SN3S UP.Browser/6.2_7.2.7.1.K.6.211 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3J')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(478386,370393,18014,841, 'KDDI-SH3J UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3Q')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(489336,370393,18014,841, 'KDDI-SN3Q UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3T')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(494306,370393,18014,841, 'KDDI-SN3T UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3F')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(474780,370393,18014,841, 'KDDI-SH3F UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473844,370393,18014,841, 'KDDI-SH3E UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3I')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(489768,370393,18014,841, 'KDDI-CA3I UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3O')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476148,370393,18014,841, 'KDDI-SN3O UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3R')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(478458,370393,18014,841, 'KDDI-SN3R UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3R')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(394649,370393,18014,841, 'KDDI-TS3R UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3N')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(474852,370393,18014,841, 'KDDI-SN3N UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3F')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473916,370393,18014,841, 'KDDI-CA3F UP.Browser/6.2_7.2.7.1.K.4.310 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3J')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(371408,370393,18014,841, 'KDDI-SN3J UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3S')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(477588,370393,18014,841, 'KDDI-TS3S UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3P')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476508,370393,18014,841, 'KDDI-SN3P UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3V')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(489048,370393,18014,841, 'KDDI-TS3V UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476220,370393,18014,841, 'KDDI-CA3H UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3J')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(490792,370393,18014,841, 'KDDI-CA3J UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3K')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(489192,370393,18014,841, 'KDDI-SH3K UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3X')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(493224,370393,18014,841, 'KDDI-TS3X UP.Browser/6.2_7.2.7.1.K.7.108 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(468629,370393,18014,841, 'KDDI-SH38 UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3O')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472475,370393,18014,841, 'KDDI-KC3O UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3W')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(489120,370393,18014,841, 'KDDI-TS3W UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(400698,370393,18014,841, 'KDDI-HI3H UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3X')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476292,370393,18014,841, 'KDDI-KC3X UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(372056,370393,18014,841, 'KDDI-SH3D UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3Z')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(478163,370393,18014,841, 'KDDI-KC3Z UP.Browser/6.2.0.16.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465529,370393,18014,841, 'KDDI-CA3C UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3L')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(491008,370393,18014,841, 'KDDI-SH3L UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3I')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(468557,370393,18014,841, 'KDDI-SN3I UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473988,370393,18014,841, 'KDDI-CA3G UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3I')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476724,370393,18014,841, 'KDDI-SH3I UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(401850,370393,18014,841, 'KDDI-SH3B UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(475140,370393,18014,841, 'KDDI-SH3G UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465673,370393,18014,841, 'KDDI-SN3G UP.Browser/6.2.0.14.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3L')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473484,370393,18014,841, 'KDDI-SN3L UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472691,370393,18014,841, 'KDDI-CA3E UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3F')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(394577,370393,18014,841, 'KDDI-SN3F UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3R')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473700,370393,18014,841, 'KDDI-KC3R UP.Browser/6.2_7.2.7.1.K.4.310 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3Q')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472619,370393,18014,841, 'KDDI-TS3Q UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456378,370393,18014,841, 'KDDI-CA3A UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(476868,370393,18014,841, 'KDDI-SH3H UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3U')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(477660,370393,18014,841, 'KDDI-TS3U UP.Browser/6.2_7.2.7.1.K.5.207 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465457,370393,18014,841, 'KDDI-HI3E UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC42')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(490864,370393,18014,841, 'KDDI-KC42 UP.Browser/6.2_7.2.7.1.K.6.210 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(455730,370393,18014,841, 'KDDI-CA39 UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3K')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(470070,370393,18014,841, 'KDDI-SN3K UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(493440,370393,18014,841, 'KDDI-PT36 UP.Browser/6.2.0.17.2.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(464667,370393,18014,841, 'KDDI-SH36 UP.Browser/6.2.0.14.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456018,370393,18014,841, 'KDDI-HI3D UP.Browser/6.2_7.2.7.1.K.2.234 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3M')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473556,370393,18014,841, 'KDDI-SN3M UP.Browser/6.2.0.14.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458682,370393,18014,841, 'KDDI-SN3E UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457170,370393,18014,841, 'KDDI-SN3B UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3N')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(468917,370393,18014,841, 'KDDI-TS3N UP.Browser/6.2_7.2.7.1.K.3.352 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(460194,370393,18014,841, 'KDDI-MA33 UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3O')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(470142,370393,18014,841, 'KDDI-TS3O UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3P')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(471293,370393,18014,841, 'KDDI-TS3P UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456090,370393,18014,841, 'KDDI-SH33 UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456882,370393,18014,841, 'KDDI-HI3B UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3I')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459690,370393,18014,841, 'KDDI-TS3I UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459114,370393,18014,841, 'KDDI-SH34 UP.Browser/6.2.0.13.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(455802,370393,18014,841, 'KDDI-SN3D UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456954,370393,18014,841, 'KDDI-KC3D UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457674,370393,18014,841, 'KDDI-TS3D UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(468773,370393,18014,841, 'KDDI-MA35 UP.Browser/6.2_7.2.7.1.K.2.232 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456162,370393,18014,841, 'KDDI-SA3A UP.Browser/6.2.0.13.1.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3I')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465745,370393,18014,841, 'KDDI-KC3I UP.Browser/6.2.0.14.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(394433,370393,18014,841, 'KDDI-TS3H UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459186,370393,18014,841, 'KDDI-CA38 UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3S')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473628,370393,18014,841, 'KDDI-KC3S UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3V')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(474996,370393,18014,841, 'KDDI-KC3V UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456378,292349,18014,841, 'KDDI-CA3A UP.Browser/6.2.0.13.2 (GUI) MMP/2.0 AppEngine-Google; (+http://code.google.com/appengine; appid: s~google.com:mobile-checker)');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457242,370393,18014,841, 'KDDI-SN3A UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457530,370393,18014,841, 'KDDI-ST33 UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457746,370393,18014,841, 'KDDI-KC3H UP.Browser/6.2.0.14.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457314,370393,18014,841, 'KDDI-KC3B UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3Q')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472547,370393,18014,841, 'KDDI-KC3Q UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458754,370393,18014,841, 'KDDI-TS3G UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459906,370393,18014,841, 'KDDI-ST34 UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458538,370393,18014,841, 'KDDI-HI3C UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458106,370393,18014,841, 'KDDI-TS3E UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3N')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(469061,370393,18014,841, 'KDDI-KC3N UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3Y')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(477156,370393,18014,841, 'KDDI-KC3Y UP.Browser/6.2.0.17.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465601,370393,18014,841, 'KDDI-MA34 UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459402,370393,18014,841, 'KDDI-SA3C UP.Browser/6.2_7.2.7.1.K.1.5.1.120 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3P')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(488976,370393,18014,841, 'KDDI-KC3P UP.Browser/6.2.0.15.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457818,370393,18014,841, 'KDDI-HI3A UP.Browser/6.2.0.13.1.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(461489,370393,18014,841, 'KDDI-PT34 UP.Browser/6.2.0.14.3.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459042,370393,18014,841, 'KDDI-PT33 UP.Browser/6.2.0.13.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3G')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459258,370393,18014,841, 'KDDI-KC3G UP.Browser/6.2.0.14.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3T')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(475068,370393,18014,841, 'KDDI-TS3T UP.Browser/6.2_7.2.7.1.K.4.306 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-AM01')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(382239,370393,22353,841, 'KDDI-AM01 UP.Browser/ KJ/ Mozilla/4.0 (REX; U; en-us; Sanyo; SCP-6750/US; NetFront/3.4/AMB)');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3K')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472331,370393,18014,841, 'KDDI-KC3K UP.Browser/6.2.0.14.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3U')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(474924,370393,18014,841, 'KDDI-KC3U UP.Browser/6.2.0.15.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3T')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(473772,370393,18014,841, 'KDDI-KC3T UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(468845,370393,18014,841, 'KDDI-PT35 UP.Browser/6.2.0.15.1.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS21')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472403,370393,441738,841, 'KDDI-TS21 UP.Browser/6.0.2.273 (GUI) MMP/1.1');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458250,370393,18014,841, 'KDDI-CA34 UP.Browser/6.2.0.10.3.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456522,370393,18014,841, 'KDDI-CA37 UP.Browser/6.2.0.12.1.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457098,370393,18014,841, 'KDDI-CA35 UP.Browser/6.2.0.11.1.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459834,370393,18014,841, 'KDDI-ST32 UP.Browser/6.2.0.13.1.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456738,370393,18014,841, 'KDDI-SA39 UP.Browser/6.2.0.12.1.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442819,370393,18014,841, 'KDDI-CA33 UP.Browser/6.2.0.10.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456234,370393,18014,841, 'KDDI-MA32 UP.Browser/6.2.0.12.1.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC28')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456666,370393,18014,841, 'KDDI-KC28 UP.Browser/6.2.0.10.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458394,370393,18014,841, 'KDDI-CA36 UP.Browser/6.2.0.10.3.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458466,370393,18014,841, 'KDDI-HI37 UP.Browser/6.2.0.10.3.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459618,370393,18014,841, 'KDDI-MA31 UP.Browser/6.2.0.11.1.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA21')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442675,370393,441738,841, 'KDDI-CA21 UP.Browser/6.0.6 (GUI) MMP/1.1');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456306,370393,18014,841, 'KDDI-HI39 UP.Browser/6.2.0.12.1.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456594,370393,18014,841, 'KDDI-SH32 UP.Browser/6.2.0.11.2.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456810,370393,18014,841, 'KDDI-HI34 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST27')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457026,370393,18014,841, 'KDDI-ST27 UP.Browser/6.2.0.9 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3J')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457458,370393,18014,841, 'KDDI-TS3J UP.Browser/6.2_7.2.7.1.K.2.179 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458178,370393,18014,841, 'KDDI-KC3E UP.Browser/6.2.0.11.1.2.2e (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458322,370393,18014,841, 'KDDI-SN36 UP.Browser/6.2.0.10.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459762,370393,18014,841, 'KDDI-HI36 UP.Browser/6.2.0.10.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST28')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459978,370393,18014,841, 'KDDI-ST28 UP.Browser/6.2.0.10.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(460050,370393,18014,841, 'KDDI-KC39 UP.Browser/6.2.0.12.1.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457386,370393,18014,841, 'KDDI-SA35 UP.Browser/6.2.0.9.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA23')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442747,370393,18014,841, 'KDDI-CA23 UP.Browser/6.2.0.5.136 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA23')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442747,370393,16149,841, 'KDDI-CA23');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS25')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442891,370393,16149,841, 'KDDI-TS25');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA27')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442963,370393,18014,841, 'KDDI-SA27 UP.Browser/6.2.0.6.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS25')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(442891,370393,441738,841, 'KDDI-TS25 UP.Browser/6.0.8.3 (GUI) MMP/1.1');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456450,370393,18014,841, 'KDDI-KC35 UP.Browser/6.2.0.10.2.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(370400,370393,16149,841, 'KDDI-CA31');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457314,370393,16149,841, 'KDDI-KC3B');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457386,370393,16149,841, 'KDDI-SA35');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457530,370393,16149,841, 'KDDI-ST33');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC2A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457602,370393,18014,841, 'KDDI-KC2A UP.Browser/6.2.0.13.3 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA29')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457890,370393,18014,841, 'KDDI-SA29 UP.Browser/6.2.0.10.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457962,370393,18014,841, 'KDDI-HI35 UP.Browser/6.2.0.9.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458034,370393,18014,841, 'KDDI-KC36 UP.Browser/6.2.0.10.2.2 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458250,370393,16149,841, 'KDDI-CA34');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA2A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458610,370393,18014,841, 'KDDI-SA2A UP.Browser/6.2.0.10.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT22')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458826,370393,18014,841, 'KDDI-PT22 UP.Browser/6.2.0.10.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458898,370393,16149,841, 'KDDI-KC33');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458970,370393,18014,841, 'KDDI-SA31 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST25')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(347077,370393,18014,841, 'KDDI-ST25 UP.Browser/6.2.0.8 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459330,370393,18014,841, 'KDDI-SN34 UP.Browser/6.2.0.10.4 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459474,370393,16149,841, 'KDDI-TS37');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459546,370393,18014,841, 'KDDI-TS32 UP.Browser/6.2.0.9.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(460122,370393,18014,841, 'KDDI-TS34 UP.Browser/6.2.0.10.2.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST26')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(460266,370393,18014,841, 'KDDI-ST26 UP.Browser/6.2.0.8 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458106,370393,16149,841, 'KDDI-TS3E');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457674,370393,16149,841, 'KDDI-TS3D');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459906,370393,16149,841, 'KDDI-ST34');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST27')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457026,370393,16149,841, 'KDDI-ST27');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3F')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(394577,370393,16149,841, 'KDDI-SN3F');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458682,370393,16149,841, 'KDDI-SN3E');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST25')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(347077,370393,16149,841, 'KDDI-ST25');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457242,370393,16149,841, 'KDDI-SN3A');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457170,370393,16149,841, 'KDDI-SN3B');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458322,370393,16149,841, 'KDDI-SN36');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SN34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459330,370393,16149,841, 'KDDI-SN34');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456090,370393,16149,841, 'KDDI-SH33');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456594,370393,16149,841, 'KDDI-SH32');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SH34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459114,370393,16149,841, 'KDDI-SH34');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA2A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458610,370393,16149,841, 'KDDI-SA2A');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456162,370393,16149,841, 'KDDI-SA3A');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459042,370393,16149,841, 'KDDI-PT33');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-PT22')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458826,370393,16149,841, 'KDDI-PT22');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3H')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457746,370393,16149,841, 'KDDI-KC3H');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456954,370393,16149,841, 'KDDI-KC3D');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-MA32')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456234,370393,16149,841, 'KDDI-MA32');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458034,370393,16149,841, 'KDDI-KC36');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456450,370393,16149,841, 'KDDI-KC35');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3B')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456882,370393,16149,841, 'KDDI-HI3B');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457818,370393,16149,841, 'KDDI-HI3A');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3D')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456018,370393,16149,841, 'KDDI-HI3D');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI39')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456306,370393,16149,841, 'KDDI-HI39');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458466,370393,16149,841, 'KDDI-HI37');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI35')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457962,370393,16149,841, 'KDDI-HI35');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI36')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459762,370393,16149,841, 'KDDI-HI36');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA3A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456378,370393,16149,841, 'KDDI-CA3A');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA38')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459186,370393,16149,841, 'KDDI-CA38');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA31')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(370400,370393,18014,841, 'KDDI-CA31 UP.Browser/6.2.0.7.3.129 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-SA29')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(457890,370393,16149,841, 'KDDI-SA29');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-CA37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456522,370393,16149,841, 'KDDI-CA37');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458538,370393,16149,841, 'KDDI-HI3C');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS37')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(459474,370393,18014,841, 'KDDI-TS37 UP.Browser/6.2.0.10.3.3.1 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI34')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(456810,370393,16149,841, 'KDDI-HI34');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC33')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(458898,370393,18014,841, 'KDDI-KC33 UP.Browser/6.2.0.9 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST21')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472187,370393,441738,841, 'KDDI-ST21 UP.Browser/6.0.8.3 (GUI) MMP/1.1');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-ST23')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472259,370393,18014,841, 'KDDI-ST23 UP.Browser/6.2.0.5 (GUI) MMP/2.0');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-HI3E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(465457,370393,16149,841, 'KDDI-HI3E');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-TS22')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(27547,370393,441738,841, 'KDDI-TS22 UP.Browser/6.0.6 (GUI) MMP/1.1');
    $ls = $ns;
  }
  $ns = E55($segments, array(0 => array(0 => 'KDDI-KC3O')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(472475,370393,16149,841, 'KDDI-KC3O');
    $ls = $ns;
  }
  return $dl;
}
