<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0.
 *
 * If a copy of the MPL was not distributed with this file, You can obtain one
 * at http://mozilla.org/MPL/2.0/.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined
 * by the Mozilla Public License, v. 2.0.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E84($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 100000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[1], $test[1], $ls, 2, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H84($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#(?<=TIANYU-KTOUCH/)[^/\\b]+#', $useragent),
    1 => fiftyone_degrees_preg_match_all('#.+#', $useragent));
  $ns = E84($segments, array(0 => array(0 => 'A630'), 1 => array(0 => 'TIANYU-KTOUCH/A630')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A630');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A660'), 1 => array(0 => 'TIANYU-KTOUCH/A660')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A660');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A662'), 1 => array(0 => 'TIANYU-KTOUCH/A662')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A662');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A691'), 1 => array(0 => 'TIANYU-KTOUCH/A691')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A691');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A907'), 1 => array(0 => 'TIANYU-KTOUCH/A907')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A907');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'B2012'), 1 => array(0 => 'TIANYU-KTOUCH/B2012')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/B2012');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'B2015'), 1 => array(0 => 'TIANYU-KTOUCH/B2015')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/B2015');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'C500'), 1 => array(0 => 'TIANYU-KTOUCH/C500')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/C500');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'C800'), 1 => array(0 => 'TIANYU-KTOUCH/C800')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/C800');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D172'), 1 => array(0 => 'TIANYU-KTOUCH/D172')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D172');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D702'), 1 => array(0 => 'TIANYU-KTOUCH/D702')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D702');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D770'), 1 => array(0 => 'TIANYU-KTOUCH/D770')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D770');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D780'), 1 => array(0 => 'TIANYU-KTOUCH/D780')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D780');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D788'), 1 => array(0 => 'TIANYU-KTOUCH/D788')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D788');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'DT28'), 1 => array(0 => 'TIANYU-KTOUCH/DT28')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/DT28');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H800'), 1 => array(0 => 'TIANYU-KTOUCH/H800')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/H800');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H711'), 1 => array(0 => 'TIANYU-KTOUCH/H711')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/H711');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V760'), 1 => array(0 => 'TIANYU-KTOUCH/V760')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/V760');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V918'), 1 => array(0 => 'TIANYU-KTOUCH/V918')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/V918');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D772'), 1 => array(0 => 'TIANYU-KTOUCH/D772/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D772/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'DT200'), 1 => array(0 => 'TIANYU-KTOUCH/DT200/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/DT200/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A610'), 1 => array(0 => 'TIANYU-KTOUCH/A610/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A610/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D159'), 1 => array(0 => 'TIANYU-KTOUCH/D159/Screen-128X128')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D159/Screen-128X128');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D175'), 1 => array(0 => 'TIANYU-KTOUCH/D175/Screen-128X160')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/D175/Screen-128X160');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'X90'), 1 => array(0 => 'TIANYU-KTOUCH/X90/MIDP2.0/CLDC1.1/Screen-320X240')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/X90/MIDP2.0/CLDC1.1/Screen-320X240');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A927'), 1 => array(0 => 'TIANYU-KTOUCH/A927/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/A927/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'FT05'), 1 => array(0 => 'TIANYU-KTOUCH/FT05/MIDP2.0/CLDC1.1/Screen-240X320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(15364,17895,17896,18092, 'TIANYU-KTOUCH/FT05/MIDP2.0/CLDC1.1/Screen-240X320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A930'), 1 => array(0 => 'TIANYU-KTOUCH/A930/Screen-240X320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17899,17895,17896,18092, 'TIANYU-KTOUCH/A930/Screen-240X320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A930'), 1 => array(0 => 'TIANYU-KTOUCH/A930/Screen-240X320 Novarra-Vision/8.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17899,17895,17896,18092, 'TIANYU-KTOUCH/A930/Screen-240X320 Novarra-Vision/8.0');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A930'), 1 => array(0 => 'TIANYU-KTOUCH/A930')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17899,17895,17896,18092, 'TIANYU-KTOUCH/A930');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H699'), 1 => array(0 => 'TIANYU-KTOUCH/H699')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17891,17895,17896,18092, 'TIANYU-KTOUCH/H699');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H699'), 1 => array(0 => 'TIANYU-KTOUCH/H699/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17891,17895,17896,18092, 'TIANYU-KTOUCH/H699/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'X260'), 1 => array(0 => 'TIANYU-KTOUCH/X260')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17884,17895,17896,18092, 'TIANYU-KTOUCH/X260');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'X260'), 1 => array(0 => 'TIANYU-KTOUCH/X260/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17884,17895,17896,18092, 'TIANYU-KTOUCH/X260/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H688'), 1 => array(0 => 'TIANYU-KTOUCH/H688/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17892,17895,17896,18092, 'TIANYU-KTOUCH/H688/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V908'), 1 => array(0 => 'TIANYU-KTOUCH/V908/MIDP2.0/CLDC1.1/Screen-240x320 Profile/MIDP-2.0 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17885,17895,17896,18092, 'TIANYU-KTOUCH/V908/MIDP2.0/CLDC1.1/Screen-240x320 Profile/MIDP-2.0 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V908'), 1 => array(0 => 'TIANYU-KTOUCH/V908')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17885,17895,17896,18092, 'TIANYU-KTOUCH/V908');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V908|V908'), 1 => array(0 => 'TIANYU-KTOUCH/V908|V908/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17885,17895,17896,18092, 'TIANYU-KTOUCH/V908|V908/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V908'), 1 => array(0 => 'TIANYU-KTOUCH/V908/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17885,17895,17896,18092, 'TIANYU-KTOUCH/V908/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H999'), 1 => array(0 => 'TIANYU-KTOUCH/H999')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17888,17895,17896,18092, 'TIANYU-KTOUCH/H999');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H999'), 1 => array(0 => 'TIANYU-KTOUCH/H999/MIDP2.0/CLDC1.1/Screen-320X240')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17888,17895,17896,18092, 'TIANYU-KTOUCH/H999/MIDP2.0/CLDC1.1/Screen-320X240');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'B832'), 1 => array(0 => 'TIANYU-KTOUCH/B832/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17897,17895,17896,18092, 'TIANYU-KTOUCH/B832/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H677'), 1 => array(0 => 'TIANYU-KTOUCH/H677/Screen-176X220')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17893,17895,17896,18092, 'TIANYU-KTOUCH/H677/Screen-176X220');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H877'), 1 => array(0 => 'TIANYU-KTOUCH/H877/MIDP2.0/CLDC1.1/Screen-320X240 Profile/MIDP-2.1 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17889,17895,17896,18092, 'TIANYU-KTOUCH/H877/MIDP2.0/CLDC1.1/Screen-320X240 Profile/MIDP-2.1 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H877'), 1 => array(0 => 'TIANYU-KTOUCH/H877')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17889,17895,17896,18092, 'TIANYU-KTOUCH/H877');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H877'), 1 => array(0 => 'TIANYU-KTOUCH/H877/MIDP2.0/CLDC1.1/Screen-320X240')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17889,17895,17896,18092, 'TIANYU-KTOUCH/H877/MIDP2.0/CLDC1.1/Screen-320X240');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'V388'), 1 => array(0 => 'TIANYU-KTOUCH/V388/MIDP2.0/CLDC1.1/Screen-240X320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17886,17895,17896,18092, 'TIANYU-KTOUCH/V388/MIDP2.0/CLDC1.1/Screen-240X320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'E62'), 1 => array(0 => 'TIANYU-KTOUCH/E62/MIDP2.0/CLDC1.1/Screen-240X400 Profile/MIDP-2.0 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17901,17895,17896,18092, 'TIANYU-KTOUCH/E62/MIDP2.0/CLDC1.1/Screen-240X400 Profile/MIDP-2.0 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'E62'), 1 => array(0 => 'TIANYU-KTOUCH/E62/MIDP2.0/CLDC1.1/Screen-240X400')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17901,17895,17896,18092, 'TIANYU-KTOUCH/E62/MIDP2.0/CLDC1.1/Screen-240X400');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H777'), 1 => array(0 => 'TIANYU-KTOUCH/H777/MIDP2.0/CLDC1.1/Screen-320X240 Profile/MIDP-2.1 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17890,17895,17896,18092, 'TIANYU-KTOUCH/H777/MIDP2.0/CLDC1.1/Screen-320X240 Profile/MIDP-2.1 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'H777'), 1 => array(0 => 'TIANYU-KTOUCH/H777/MIDP2.0/CLDC1.1/Screen-320X240')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17890,17895,17896,18092, 'TIANYU-KTOUCH/H777/MIDP2.0/CLDC1.1/Screen-320X240');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A7726'), 1 => array(0 => 'TIANYU-KTOUCH/A7726/MIDP2.0/CLDC1.1/Screen-240x320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17900,17895,17896,18092, 'TIANYU-KTOUCH/A7726/MIDP2.0/CLDC1.1/Screen-240x320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'B2010'), 1 => array(0 => 'TIANYU-KTOUCH/B2010/Screen-128X128')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17898,17895,17896,18092, 'TIANYU-KTOUCH/B2010/Screen-128X128');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'D6600'), 1 => array(0 => 'TIANYU-KTOUCH/D6600/Screen-240X432')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17894,17895,17896,18092, 'TIANYU-KTOUCH/D6600/Screen-240X432');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'L65'), 1 => array(0 => 'TIANYU-KTOUCH/L65/Screen-240X320')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17887,17895,17896,18092, 'TIANYU-KTOUCH/L65/Screen-240X320');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A665'), 1 => array(0 => 'TIANYU-KTOUCH/A665/MIDP2.0/CLDC1.1/Screen-240X320 Profile/MIDP-2.0 Configuration/CLDC-1.1')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17902,17895,17896,18092, 'TIANYU-KTOUCH/A665/MIDP2.0/CLDC1.1/Screen-240X320 Profile/MIDP-2.0 Configuration/CLDC-1.1');
    $ls = $ns;
  }
  $ns = E84($segments, array(0 => array(0 => 'A665'), 1 => array(0 => 'TIANYU-KTOUCH/A665')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(17902,17895,17896,18092, 'TIANYU-KTOUCH/A665');
    $ls = $ns;
  }
  return $dl;
}
